### ISSUE TITLE
"Internal error" on iOS app

### ISSUE THREAD

**Issue by omdv** [vvondra/bitwarden-serverless#29]
Hello, first of all thanks for the great code. I deployed it and confirmed that it works well with desktop app (on mac OS). However when I try to login on iOS using the login created on desktop app it gives me the "Internal error". I wish I had more debug details, but I don't. 

With this said - if I sign up for a new account using iOS app it goes through and I can then login using desktop app. But I still cannot login using iOS app, even if I signed up using iOS app.

Any ideas on what to try next or how to debug it further?

**Comment by vvondra** [comment]
I just pushed a fix, the problem was that the iOS sends an additional device type field.

To debug, it was simply visible in `sls logs -f login`, it took me longer to get hands on an iPhone to test.

**Comment by omdv** [comment]
Thanks for a prompt response. I pulled the other branch and redeployed. The problem is still there, although may be the different one. Part of `sls logs -f login` (let me know if you need all of it):

```
2018-08-28 17:30:15.467 (-05:00)	ee8de352-ab11-11e8-8a5e-41086ead07f0	Server error { message: 'Internal error',
  error: TypeError: Cannot read property 'toString' of undefined
    at /var/task/src/login.js:58369:45
    at Generator.next (<anonymous>)
    at step (/var/task/src/login.js:58224:191)
    at /var/task/src/login.js:58224:361
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) }
```

**Comment by vvondra** [comment]
Thanks, fixed that one now.
